### ISSUE TITLE
No generate button and error with line 21

### ISSUE THREAD

**Issue by Crastinum** [MrHaCkEr/Wuxiaworld-2-eBook#7]
The script runs and opens up the window to select the novel and input chapters, but there is no generate button. In cmd, I get this error for line 21:
![image](https://user-images.githubusercontent.com/33235859/32195327-5d0d35c6-bd93-11e7-885b-d16010ae4ac9.png)

**Comment by MrHaCkEr** [comment]
Could you post a picture of the GUI?
The error you see can be ignored because "book_number_choosen" is defined after line 21.
Try changing line 10 in "wuxiaworld2ebook.py" to `main.resizable(True, True)` and try resizing the window.

**Comment by Crastinum** [comment]
Thanks, it works now! Didn't realize it was further to the right. This is what it looks like before resizing it:
![image](https://user-images.githubusercontent.com/33235859/32226823-069de338-be20-11e7-8779-62c5ca927435.png)

**Comment by MrHaCkEr** [comment]
I modified wuxiaworld2ebook.py to be resizable in case somebody has the same problem
