### ISSUE TITLE
new novels

### ISSUE THREAD

**Issue by jojkov** [MrHaCkEr/Wuxiaworld-2-eBook#9]
Hi, thank you very much for this! There were some new novels in the meantime (like Overgeard), could you please add them too?

**Comment by MrHaCkEr** [comment]
As soon as I find the time.
If you can make a list with the new novels added after talisman emperor it would be faster.

**Comment by jojkov** [comment]
Cool! Ok, no problem, i will sort it today.

**Comment by jojkov** [comment]
This is the list, i added those which you labeled as "not implemented" in last 1.3 version too.
I wonder, if you could make the executable file again, if it is not too time consuming.
[WuxiaNewNovels.txt](https://github.com/MrHaCkEr/Wuxiaworld-2-eBook/files/1546776/WuxiaNewNovels.txt)

**Comment by MrHaCkEr** [comment]
Thanks for the list! I try to add the missing novels after work.
I had some troubles implementing the database to the executable, if I find a solution, I’ll release a executable.

**Comment by jojkov** [comment]
No problem, nice! Well, it worked for me (all exe versions) except for those "not implemented" novels.

**Comment by MrHaCkEr** [comment]
Added the missing novels: City of Sin, Overgeared, The Divine Elements, TranXending Vision.
Also added novels to the README, that won't be implemented in the near future, because of program limitations.
No ETA for the executable.
